/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
		/*********************Core Periphelarls Begins********************/
#include "CortexM3/CortexM3_NVIC.h"
#include "CortexM3/CortexM3_SCB.h"
#include "CortexM3/CortexM3_SysTick.h"
			/*********************Core Periphelarls Ends********************/

			/*********************MCAL Begins********************/
#include "MCAL_Drivers/EXTI.h"
#include "MCAL_Drivers/gpio.h"
#include "MCAL_Drivers/STM32F103C8T6_RCC.h"
#include "MCAL_Drivers/USART.h"
			/*********************MCAL Ends********************/

			/**********************Common Library***********************/
#include "Common/BIT_Math.h"
#include "Common/Std_Types.h"





int main(void)
{
	//Clock Configuration
	RCC_EnableHSE();
	RCC_EnablePeriphalClk(APB2_BUS, GPIOA_EN);
	RCC_EnablePeriphalClk(APB2_BUS, GPIOB_EN);
	RCC_EnablePeriphalClk(APB2_BUS, GPIOC_EN);
	RCC_EnablePeriphalClk(APB2_BUS, USART1_EN);
	RCC_EnablePeriphalClk(APB2_BUS, AFIO_EN);

	//USART1 PINS INIT
	GPIO_Init(PORTA, PIN9, OUTPUT_10MHZ, OUTPUT_ALF_PUSH_PULL);
	GPIO_Init(PORTA, PIN10, INPUT, INPUT_PULL);

	//LEDs INIT
	GPIO_Init(PORTC, PIN13, OUTPUT_10MHZ, OUTPUT_PUSH_PULL);
	GPIO_Init(PORTB, PIN0, OUTPUT_10MHZ,OUTPUT_PUSH_PULL);

	//USART
	USART_Init(USART_ID_1);

	//Systick init
	SysTick_Init();

	//Variable
	uint8_t Value;

	while(1)
	{
		//PC13 always high
		GPIO_WritePinValue(PORTC, PIN13, PIN_HIGH);

		Value = USART_RecieveByteSynch(USART_ID_1);
		if(Value == 'a')
		{
			//some action on the car
			GPIO_WritePinValue(PORTB, PIN0, PIN_HIGH);
			SysTick_WaitBlocking(79998);
		}
		else if(Value == 'b')
		{
			GPIO_WritePinValue(PORTB, PIN0, PIN_LOW);
			SysTick_WaitBlocking(79998);
		}
	}
}


